version: '3.8'
services:
  db:
    container_name: postgres_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "ecom"
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  adminer:
    image: adminer:latest
    restart: always
    container_name: adminer
    ports:
    - "8080:8080"
    depends_on:
      - 'db'

volumes:
  postgres_data: 