version: '3.8'

services:
  db:
    container_name: postgres_db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  adminer:
    image: adminer:latest
    container_name: adminer
    posts:
    - "8080:8080"
    depends_on:
      - postgres_db

volumes:
  postgres_data: 